/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor.index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as InstitutionIndexRouteImport } from './routes/institution.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SupervisorTraineesRouteImport } from './routes/supervisor.trainees'
import { Route as SupervisorSignatureRouteImport } from './routes/supervisor.signature'
import { Route as SupervisorNotificationsRouteImport } from './routes/supervisor.notifications'
import { Route as SupervisorApprovalsRouteImport } from './routes/supervisor.approvals'
import { Route as RegisterSupervisorRouteImport } from './routes/register.supervisor'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as InstitutionStudentsRouteImport } from './routes/institution.students'
import { Route as InstitutionExportRouteImport } from './routes/institution.export'
import { Route as InstitutionApprovalsRouteImport } from './routes/institution.approvals'
import { Route as InstitutionAnalyticsRouteImport } from './routes/institution.analytics'
import { Route as DashboardReportRouteImport } from './routes/dashboard.report'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardEvidenceRouteImport } from './routes/dashboard.evidence'
import { Route as DashboardDailyLogRouteImport } from './routes/dashboard.daily-log'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as SupervisorNewTraineesRouteImport } from './routes/supervisor.new.trainees'
import { Route as InstitutionAssignStudentsRouteImport } from './routes/institution.assign.students'
import { Route as DashboardNewDailyLogRouteImport } from './routes/dashboard.new.daily-log'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupervisorTraineesRoute = SupervisorTraineesRouteImport.update({
  id: '/trainees',
  path: '/trainees',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorSignatureRoute = SupervisorSignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorNotificationsRoute = SupervisorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorApprovalsRoute = SupervisorApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => SupervisorRoute,
} as any)
const RegisterSupervisorRoute = RegisterSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => RegisterRoute,
} as any)
const InstitutionStudentsRoute = InstitutionStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionExportRoute = InstitutionExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionApprovalsRoute = InstitutionApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionAnalyticsRoute = InstitutionAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InstitutionRoute,
} as any)
const DashboardReportRoute = DashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvidenceRoute = DashboardEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDailyLogRoute = DashboardDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const SupervisorNewTraineesRoute = SupervisorNewTraineesRouteImport.update({
  id: '/new/trainees',
  path: '/new/trainees',
  getParentRoute: () => SupervisorRoute,
} as any)
const InstitutionAssignStudentsRoute =
  InstitutionAssignStudentsRouteImport.update({
    id: '/assign/students',
    path: '/assign/students',
    getParentRoute: () => InstitutionRoute,
  } as any)
const DashboardNewDailyLogRoute = DashboardNewDailyLogRouteImport.update({
  id: '/new/daily-log',
  path: '/new/daily-log',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/daily-log': typeof DashboardDailyLogRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/institution/analytics': typeof InstitutionAnalyticsRoute
  '/institution/approvals': typeof InstitutionApprovalsRoute
  '/institution/export': typeof InstitutionExportRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/supervisor': typeof RegisterSupervisorRoute
  '/supervisor/approvals': typeof SupervisorApprovalsRoute
  '/supervisor/notifications': typeof SupervisorNotificationsRoute
  '/supervisor/signature': typeof SupervisorSignatureRoute
  '/supervisor/trainees': typeof SupervisorTraineesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/dashboard/new/daily-log': typeof DashboardNewDailyLogRoute
  '/institution/assign/students': typeof InstitutionAssignStudentsRoute
  '/supervisor/new/trainees': typeof SupervisorNewTraineesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/daily-log': typeof DashboardDailyLogRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/institution/analytics': typeof InstitutionAnalyticsRoute
  '/institution/approvals': typeof InstitutionApprovalsRoute
  '/institution/export': typeof InstitutionExportRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/supervisor': typeof RegisterSupervisorRoute
  '/supervisor/approvals': typeof SupervisorApprovalsRoute
  '/supervisor/notifications': typeof SupervisorNotificationsRoute
  '/supervisor/signature': typeof SupervisorSignatureRoute
  '/supervisor/trainees': typeof SupervisorTraineesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/institution': typeof InstitutionIndexRoute
  '/register': typeof RegisterIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
  '/dashboard/new/daily-log': typeof DashboardNewDailyLogRoute
  '/institution/assign/students': typeof InstitutionAssignStudentsRoute
  '/supervisor/new/trainees': typeof SupervisorNewTraineesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/daily-log': typeof DashboardDailyLogRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/institution/analytics': typeof InstitutionAnalyticsRoute
  '/institution/approvals': typeof InstitutionApprovalsRoute
  '/institution/export': typeof InstitutionExportRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/supervisor': typeof RegisterSupervisorRoute
  '/supervisor/approvals': typeof SupervisorApprovalsRoute
  '/supervisor/notifications': typeof SupervisorNotificationsRoute
  '/supervisor/signature': typeof SupervisorSignatureRoute
  '/supervisor/trainees': typeof SupervisorTraineesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/dashboard/new/daily-log': typeof DashboardNewDailyLogRoute
  '/institution/assign/students': typeof InstitutionAssignStudentsRoute
  '/supervisor/new/trainees': typeof SupervisorNewTraineesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/institution'
    | '/login'
    | '/register'
    | '/supervisor'
    | '/verify-otp'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/calendar'
    | '/dashboard/daily-log'
    | '/dashboard/evidence'
    | '/dashboard/notifications'
    | '/dashboard/report'
    | '/institution/analytics'
    | '/institution/approvals'
    | '/institution/export'
    | '/institution/students'
    | '/register/student'
    | '/register/supervisor'
    | '/supervisor/approvals'
    | '/supervisor/notifications'
    | '/supervisor/signature'
    | '/supervisor/trainees'
    | '/admin/'
    | '/dashboard/'
    | '/institution/'
    | '/register/'
    | '/supervisor/'
    | '/dashboard/new/daily-log'
    | '/institution/assign/students'
    | '/supervisor/new/trainees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/verify-otp'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/calendar'
    | '/dashboard/daily-log'
    | '/dashboard/evidence'
    | '/dashboard/notifications'
    | '/dashboard/report'
    | '/institution/analytics'
    | '/institution/approvals'
    | '/institution/export'
    | '/institution/students'
    | '/register/student'
    | '/register/supervisor'
    | '/supervisor/approvals'
    | '/supervisor/notifications'
    | '/supervisor/signature'
    | '/supervisor/trainees'
    | '/admin'
    | '/dashboard'
    | '/institution'
    | '/register'
    | '/supervisor'
    | '/dashboard/new/daily-log'
    | '/institution/assign/students'
    | '/supervisor/new/trainees'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/institution'
    | '/login'
    | '/register'
    | '/supervisor'
    | '/verify-otp'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/calendar'
    | '/dashboard/daily-log'
    | '/dashboard/evidence'
    | '/dashboard/notifications'
    | '/dashboard/report'
    | '/institution/analytics'
    | '/institution/approvals'
    | '/institution/export'
    | '/institution/students'
    | '/register/student'
    | '/register/supervisor'
    | '/supervisor/approvals'
    | '/supervisor/notifications'
    | '/supervisor/signature'
    | '/supervisor/trainees'
    | '/admin/'
    | '/dashboard/'
    | '/institution/'
    | '/register/'
    | '/supervisor/'
    | '/dashboard/new/daily-log'
    | '/institution/assign/students'
    | '/supervisor/new/trainees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstitutionRoute: typeof InstitutionRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SupervisorRoute: typeof SupervisorRouteWithChildren
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/institution/': {
      id: '/institution/'
      path: '/'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supervisor/trainees': {
      id: '/supervisor/trainees'
      path: '/trainees'
      fullPath: '/supervisor/trainees'
      preLoaderRoute: typeof SupervisorTraineesRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/signature': {
      id: '/supervisor/signature'
      path: '/signature'
      fullPath: '/supervisor/signature'
      preLoaderRoute: typeof SupervisorSignatureRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/notifications': {
      id: '/supervisor/notifications'
      path: '/notifications'
      fullPath: '/supervisor/notifications'
      preLoaderRoute: typeof SupervisorNotificationsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/approvals': {
      id: '/supervisor/approvals'
      path: '/approvals'
      fullPath: '/supervisor/approvals'
      preLoaderRoute: typeof SupervisorApprovalsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/register/supervisor': {
      id: '/register/supervisor'
      path: '/supervisor'
      fullPath: '/register/supervisor'
      preLoaderRoute: typeof RegisterSupervisorRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/student': {
      id: '/register/student'
      path: '/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/institution/students': {
      id: '/institution/students'
      path: '/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof InstitutionStudentsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/export': {
      id: '/institution/export'
      path: '/export'
      fullPath: '/institution/export'
      preLoaderRoute: typeof InstitutionExportRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/approvals': {
      id: '/institution/approvals'
      path: '/approvals'
      fullPath: '/institution/approvals'
      preLoaderRoute: typeof InstitutionApprovalsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/analytics': {
      id: '/institution/analytics'
      path: '/analytics'
      fullPath: '/institution/analytics'
      preLoaderRoute: typeof InstitutionAnalyticsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/dashboard/report': {
      id: '/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evidence': {
      id: '/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof DashboardEvidenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/daily-log': {
      id: '/dashboard/daily-log'
      path: '/daily-log'
      fullPath: '/dashboard/daily-log'
      preLoaderRoute: typeof DashboardDailyLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supervisor/new/trainees': {
      id: '/supervisor/new/trainees'
      path: '/new/trainees'
      fullPath: '/supervisor/new/trainees'
      preLoaderRoute: typeof SupervisorNewTraineesRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/institution/assign/students': {
      id: '/institution/assign/students'
      path: '/assign/students'
      fullPath: '/institution/assign/students'
      preLoaderRoute: typeof InstitutionAssignStudentsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/dashboard/new/daily-log': {
      id: '/dashboard/new/daily-log'
      path: '/new/daily-log'
      fullPath: '/dashboard/new/daily-log'
      preLoaderRoute: typeof DashboardNewDailyLogRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDailyLogRoute: typeof DashboardDailyLogRoute
  DashboardEvidenceRoute: typeof DashboardEvidenceRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReportRoute: typeof DashboardReportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardNewDailyLogRoute: typeof DashboardNewDailyLogRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDailyLogRoute: DashboardDailyLogRoute,
  DashboardEvidenceRoute: DashboardEvidenceRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReportRoute: DashboardReportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardNewDailyLogRoute: DashboardNewDailyLogRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InstitutionRouteChildren {
  InstitutionAnalyticsRoute: typeof InstitutionAnalyticsRoute
  InstitutionApprovalsRoute: typeof InstitutionApprovalsRoute
  InstitutionExportRoute: typeof InstitutionExportRoute
  InstitutionStudentsRoute: typeof InstitutionStudentsRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
  InstitutionAssignStudentsRoute: typeof InstitutionAssignStudentsRoute
}

const InstitutionRouteChildren: InstitutionRouteChildren = {
  InstitutionAnalyticsRoute: InstitutionAnalyticsRoute,
  InstitutionApprovalsRoute: InstitutionApprovalsRoute,
  InstitutionExportRoute: InstitutionExportRoute,
  InstitutionStudentsRoute: InstitutionStudentsRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
  InstitutionAssignStudentsRoute: InstitutionAssignStudentsRoute,
}

const InstitutionRouteWithChildren = InstitutionRoute._addFileChildren(
  InstitutionRouteChildren,
)

interface RegisterRouteChildren {
  RegisterStudentRoute: typeof RegisterStudentRoute
  RegisterSupervisorRoute: typeof RegisterSupervisorRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterStudentRoute: RegisterStudentRoute,
  RegisterSupervisorRoute: RegisterSupervisorRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface SupervisorRouteChildren {
  SupervisorApprovalsRoute: typeof SupervisorApprovalsRoute
  SupervisorNotificationsRoute: typeof SupervisorNotificationsRoute
  SupervisorSignatureRoute: typeof SupervisorSignatureRoute
  SupervisorTraineesRoute: typeof SupervisorTraineesRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
  SupervisorNewTraineesRoute: typeof SupervisorNewTraineesRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorApprovalsRoute: SupervisorApprovalsRoute,
  SupervisorNotificationsRoute: SupervisorNotificationsRoute,
  SupervisorSignatureRoute: SupervisorSignatureRoute,
  SupervisorTraineesRoute: SupervisorTraineesRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
  SupervisorNewTraineesRoute: SupervisorNewTraineesRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstitutionRoute: InstitutionRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SupervisorRoute: SupervisorRouteWithChildren,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
